### PR TITLE
Remove ignored file and set license-eye

### PR DESCRIPTION
**Pull request by kezhenxu94**

### CODE REVIEW

**Review by wu-sheng — COMMENTED** [review]
CI fails.

**Comment by Humbertzhang** [comment]
Maybe a licenserc.yaml should be added?

**Comment by kezhenxu94** [comment]
I use a commit hash in the license-eye action, I think this can be merged for now as 

1. we don't need a release of license-eye in order to use it HERE
2. even we have a release of license-eye, it's a good practice to use a commit hash instead of a tag

**Review by fgksgf — APPROVED** [review]

**Comment by kezhenxu94** [comment]
The `.asf.yaml` should work now (it was still `default branch==master` in gitbox and the infra just update that for us)

**Comment by wu-sheng** [comment]
> even we have a release of license-eye, it's a good practice to use a commit hash instead of a tag

Could you share the reason of this suggestion?

**Comment by kezhenxu94** [comment]
> > even we have a release of license-eye, it's a good practice to use a commit hash instead of a tag
> 
> Could you share the reason of this suggestion?

Because tags can be modified (e.g. you can push malicious codes and retag), https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/finding-and-customizing-actions#using-shas this is also recommended by the infra team during the recent security issues

**Comment by wu-sheng** [comment]
Got it.

**Pull request merged**
