### PR TITLE
Fix the GHA docker compose wait strategy failure

### PR DESCRIPTION
**Pull request by mrproliu**
Fix the docker compose wait for IP port failure when using GitHub Action.
I found it's a bug in [testcontainers-go](https://github.com/testcontainers/testcontainers-go).

I have already [submit a PR to track this one](https://github.com/testcontainers/testcontainers-go/pull/349), before that one merge and release, I provide related code into our project and fix the bug, filename called `compose-provider.go`. After this PR have been merge and release, I could remove useless code and use `testcontainers-go` project to verify the docker service health again.

### CODE REVIEW

**Comment by wu-sheng** [comment]
Please fix the CI.

**Comment by wu-sheng** [comment]
@kezhenxu94 Could you take a review on this?

**Comment by kezhenxu94** [comment]
With https://github.com/apache/skywalking-infra-e2e/pull/37 , this is not a blocker and we can wait for testcontainer-go upstream to process @mrproliu 's PR

**Review by kezhenxu94 — APPROVED** [review]
It's @mrproliu your call whether to merge this and test first, or wait for upstream PR merged

**Pull request merged**
