### PR TITLE
Let `compose` support `setup.steps`

### PR DESCRIPTION
**Pull request by mrproliu**
Follow #25

### CODE REVIEW

**Comment by wu-sheng** [comment]
What is setup step?

**Comment by mrproliu** [comment]
> What is setup step?

That means the user could execute some command in the `setup` phase, such install some software for `verify`.

**Comment by wu-sheng** [comment]
Then why this supports in compose?

**Comment by wu-sheng** [comment]
Should this be the core steps?

**Comment by mrproliu** [comment]
> Then why this supports in compose?

Currently, the `kind` is supported, It also needs to be supported. Because In the `verify` phase It running in the main process, not `compose` pods. So we need to install some software to help `verify`.

**Comment by mrproliu** [comment]
> Should this be the core steps?

It's an optional config for users, If they don't need this, just don't need to set it.

**Comment by wu-sheng** [comment]
If our verifier needs that, why doesn't it include in default?
Of course, this feature is necessary, I just ask for more.

**Comment by mrproliu** [comment]
> If our verifier needs that, why doesn't it include in default?
> Of course, this feature is necessary, I just ask for more.

There have two reasons:
1. For now, `infra-e2e` just working on the skywalking projects, it's fine. But If some other projects want to use it, maybe the software install is not necessary. So we need to move the as the optional, not include in default.
2. When the user uses the `infra-e2e` maybe they don't install the software for verifying, so we could automatically install some software before running the `verify` phase, users just need to use `e2e setup` to run it for install softwares.

**Comment by kezhenxu94** [comment]
> If our verifier needs that, why doesn't it include in default?

Our (SkyWalking) verifier needs it but not all projects using e2e need it. We don’t want to couple tightly with skywalking no?

**Comment by wu-sheng** [comment]
I think yaml or json based verification is always recommended by us. If that tool relates to this, we should make them in default. Otherwise, people and we have to install it one by one.

**Comment by mrproliu** [comment]
> I think yaml or json based verification is always recommended by us. If that tool relates to this, we should make them in default. Otherwise, people and we have to install it one by one.

You're right, Should I need to install it to GHA in default? but I think `setup.steps` should also both works in `compose`and `kind`.

**Comment by wu-sheng** [comment]
Make sense.

**Comment by kezhenxu94** [comment]
As I said, this tool is not always needed in every project, also installing it in GHA is definitely not acceptable because that would make local test fail and inconsistent with GHA. 

No matter how, this PR is needed and you can continue this PR regardless whether we should install the tool by default, it can be done in another PR if conclusion is made.

**Comment by wu-sheng** [comment]
> As I said, this tool is not always needed in every project

What does this mean exactly?

**Comment by kezhenxu94** [comment]
> > As I said, this tool is not always needed in every project
> 
> What does this mean exactly?

The softwares installed in `steps` (`yq` in this PR) are not needed in every project.

**Comment by wu-sheng** [comment]
If that is a part of yaml verifier, from the design level, it is required in default. If there is other case, we could continue to talk about details.

**Comment by Humbertzhang** [comment]
As @kezhenxu94 said, If we install it in GHA, there will be a inconsistent between GHA and user’s local environment, as  yq is not a default command.
If this tool is always needed OR its our recommended practice to use yaml for verification, maybe we should just include this tool in our `skywalking-infra-e2e` tool, rather than install it?

**Comment by mrproliu** [comment]
> As @kezhenxu94 said, If we install it in GHA, there will be a inconsistent between GHA and user’s local environment, as  yq is not a default command.
> 
> If this tool is always needed OR its our recommended practice to use yaml for verification, maybe we should just include this tool in our `skywalking-infra-e2e` tool, rather than install it?

Could you do more explain what's that mean about include? Users how to use it?

**Comment by Humbertzhang** [comment]
> Could you do more explain what's that mean about include? Users how to use it?

Maybe we can just take `yq` as a sub command of `e2e`, but this is not a conventional approach.

**Comment by mrproliu** [comment]
> > Could you do more explain what's that mean about include? Users how to use it?
> 
> Maybe we can just take `yq` as a sub command of `e2e`, but this is not a conventional approach.

Yes, maybe that's a not good practice. If we have other software that needs to be installed, should we also need to add some sub-command?

**Review by kezhenxu94 — APPROVED** [review]
This PR is to provide the same ability for `docker-compose` as `kind` to allow users to run arbitrary commands in setup, as for whether we should embed the `yq` command in this project, @mrproliu could you open a separate issue to track the discussion and merge this PR to unblock for now? @Humbertzhang please also review the codes 🙇🏻

**Review by Humbertzhang — APPROVED** [review]
LGTM!

**Pull request merged**
